<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xl2sCQIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xl2sCQI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xl2sCQI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'review' => ['privates', '.errored..service_locator.Xl2sCQI.App\\Entity\\Review', NULL, 'Cannot autowire service ".service_locator.Xl2sCQI": it needs an instance of "App\\Entity\\Review" but this type has been excluded in "config/services.yaml".'],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
        ], [
            'review' => 'App\\Entity\\Review',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
        ]);
    }
}
