<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1aa9WV_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1aa9WV.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1aa9WV.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'city' => ['privates', '.errored..service_locator.1aa9WV..App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.1aa9WV.": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".'],
            'cityRepository' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService', true],
        ], [
            'city' => 'App\\Entity\\City',
            'cityRepository' => 'App\\Repository\\CityRepository',
        ]);
    }
}
