<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GThU4KqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gThU4Kq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gThU4Kq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'craftsman' => ['privates', '.errored..service_locator.gThU4Kq.App\\Entity\\Craftsman', NULL, 'Cannot autowire service ".service_locator.gThU4Kq": it needs an instance of "App\\Entity\\Craftsman" but this type has been excluded in "config/services.yaml".'],
            'craftsmanRepository' => ['privates', 'App\\Repository\\CraftsmanRepository', 'getCraftsmanRepositoryService', true],
        ], [
            'craftsman' => 'App\\Entity\\Craftsman',
            'craftsmanRepository' => 'App\\Repository\\CraftsmanRepository',
        ]);
    }
}
