<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YF3RXzpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yF3RXzp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yF3RXzp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'craftsman' => ['privates', '.errored..service_locator.yF3RXzp.App\\Entity\\Craftsman', NULL, 'Cannot autowire service ".service_locator.yF3RXzp": it needs an instance of "App\\Entity\\Craftsman" but this type has been excluded in "config/services.yaml".'],
        ], [
            'craftsman' => 'App\\Entity\\Craftsman',
        ]);
    }
}
