<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraftsmanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gThU4Kq.App\Entity\Craftsman' shared service.
     *
     * @return \App\Entity\Craftsman
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gThU4Kq": it needs an instance of "App\\Entity\\Craftsman" but this type has been excluded in "config/services.yaml".');
    }
}
