<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_AutoCommand_MakeAutocompleteFieldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.auto_command.make_autocomplete_field' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Command\MakerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/MakerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/Maker/MakeAutocompleteField.php';

        $container->privates['maker.auto_command.make_autocomplete_field'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Symfony\UX\Autocomplete\Maker\MakeAutocompleteField(($container->privates['maker.doctrine_helper'] ?? $container->load('getMaker_DoctrineHelperService'))), ($container->privates['maker.file_manager'] ?? $container->load('getMaker_FileManagerService')), ($container->privates['maker.generator'] ?? $container->load('getMaker_GeneratorService')));

        $instance->setName('make:autocomplete-field');
        $instance->setDescription('Generates an Ajax-autocomplete form field class for symfony/ux-autocomplete.');

        return $instance;
    }
}
