<?php

namespace ContainerKdnUcK1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_EntityTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.autocomplete.entity_type' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/Form/ParentEntityAutocompleteType.php';

        return $container->privates['ux.autocomplete.entity_type'] = new \Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType(($container->services['router'] ?? $container->getRouterService()));
    }
}
