<?php

namespace ContainerEjIPlpG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Maker_AutoCommand_MakeAutocompleteField_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.maker.auto_command.make_autocomplete_field.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.maker.auto_command.make_autocomplete_field.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:autocomplete-field', [], 'Generates an Ajax-autocomplete form field class for symfony/ux-autocomplete.', false, #[\Closure(name: 'maker.auto_command.make_autocomplete_field', class: 'Symfony\\Bundle\\MakerBundle\\Command\\MakerCommand')] function () use ($container): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
            return ($container->privates['maker.auto_command.make_autocomplete_field'] ?? $container->load('getMaker_AutoCommand_MakeAutocompleteFieldService'));
        });
    }
}
