<?php

namespace ContainerEjIPlpG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Go7rx2QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.go7rx2Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.go7rx2Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CityController::delete' => ['privates', '.service_locator.1aa9WV.', 'get_ServiceLocator_1aa9WV_Service', true],
            'App\\Controller\\CityController::edit' => ['privates', '.service_locator.1aa9WV.', 'get_ServiceLocator_1aa9WV_Service', true],
            'App\\Controller\\CityController::index' => ['privates', '.service_locator.mkff3Zb', 'get_ServiceLocator_Mkff3ZbService', true],
            'App\\Controller\\CityController::new' => ['privates', '.service_locator.mkff3Zb', 'get_ServiceLocator_Mkff3ZbService', true],
            'App\\Controller\\CityController::show' => ['privates', '.service_locator.ycxdVNz', 'get_ServiceLocator_YcxdVNzService', true],
            'App\\Controller\\CraftsmanController::delete' => ['privates', '.service_locator.gThU4Kq', 'get_ServiceLocator_GThU4KqService', true],
            'App\\Controller\\CraftsmanController::edit' => ['privates', '.service_locator.gThU4Kq', 'get_ServiceLocator_GThU4KqService', true],
            'App\\Controller\\CraftsmanController::index' => ['privates', '.service_locator.rTw_0vv', 'get_ServiceLocator_RTw0vvService', true],
            'App\\Controller\\CraftsmanController::new' => ['privates', '.service_locator.rTw_0vv', 'get_ServiceLocator_RTw0vvService', true],
            'App\\Controller\\CraftsmanController::show' => ['privates', '.service_locator.yF3RXzp', 'get_ServiceLocator_YF3RXzpService', true],
            'App\\Controller\\ProfessionController::delete' => ['privates', '.service_locator.NPKxTRT', 'get_ServiceLocator_NPKxTRTService', true],
            'App\\Controller\\ProfessionController::edit' => ['privates', '.service_locator.NPKxTRT', 'get_ServiceLocator_NPKxTRTService', true],
            'App\\Controller\\ProfessionController::index' => ['privates', '.service_locator.fQ8zT5J', 'get_ServiceLocator_FQ8zT5JService', true],
            'App\\Controller\\ProfessionController::new' => ['privates', '.service_locator.fQ8zT5J', 'get_ServiceLocator_FQ8zT5JService', true],
            'App\\Controller\\ProfessionController::show' => ['privates', '.service_locator.eXwxcMx', 'get_ServiceLocator_EXwxcMxService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CityController:delete' => ['privates', '.service_locator.1aa9WV.', 'get_ServiceLocator_1aa9WV_Service', true],
            'App\\Controller\\CityController:edit' => ['privates', '.service_locator.1aa9WV.', 'get_ServiceLocator_1aa9WV_Service', true],
            'App\\Controller\\CityController:index' => ['privates', '.service_locator.mkff3Zb', 'get_ServiceLocator_Mkff3ZbService', true],
            'App\\Controller\\CityController:new' => ['privates', '.service_locator.mkff3Zb', 'get_ServiceLocator_Mkff3ZbService', true],
            'App\\Controller\\CityController:show' => ['privates', '.service_locator.ycxdVNz', 'get_ServiceLocator_YcxdVNzService', true],
            'App\\Controller\\CraftsmanController:delete' => ['privates', '.service_locator.gThU4Kq', 'get_ServiceLocator_GThU4KqService', true],
            'App\\Controller\\CraftsmanController:edit' => ['privates', '.service_locator.gThU4Kq', 'get_ServiceLocator_GThU4KqService', true],
            'App\\Controller\\CraftsmanController:index' => ['privates', '.service_locator.rTw_0vv', 'get_ServiceLocator_RTw0vvService', true],
            'App\\Controller\\CraftsmanController:new' => ['privates', '.service_locator.rTw_0vv', 'get_ServiceLocator_RTw0vvService', true],
            'App\\Controller\\CraftsmanController:show' => ['privates', '.service_locator.yF3RXzp', 'get_ServiceLocator_YF3RXzpService', true],
            'App\\Controller\\ProfessionController:delete' => ['privates', '.service_locator.NPKxTRT', 'get_ServiceLocator_NPKxTRTService', true],
            'App\\Controller\\ProfessionController:edit' => ['privates', '.service_locator.NPKxTRT', 'get_ServiceLocator_NPKxTRTService', true],
            'App\\Controller\\ProfessionController:index' => ['privates', '.service_locator.fQ8zT5J', 'get_ServiceLocator_FQ8zT5JService', true],
            'App\\Controller\\ProfessionController:new' => ['privates', '.service_locator.fQ8zT5J', 'get_ServiceLocator_FQ8zT5JService', true],
            'App\\Controller\\ProfessionController:show' => ['privates', '.service_locator.eXwxcMx', 'get_ServiceLocator_EXwxcMxService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CityController::delete' => '?',
            'App\\Controller\\CityController::edit' => '?',
            'App\\Controller\\CityController::index' => '?',
            'App\\Controller\\CityController::new' => '?',
            'App\\Controller\\CityController::show' => '?',
            'App\\Controller\\CraftsmanController::delete' => '?',
            'App\\Controller\\CraftsmanController::edit' => '?',
            'App\\Controller\\CraftsmanController::index' => '?',
            'App\\Controller\\CraftsmanController::new' => '?',
            'App\\Controller\\CraftsmanController::show' => '?',
            'App\\Controller\\ProfessionController::delete' => '?',
            'App\\Controller\\ProfessionController::edit' => '?',
            'App\\Controller\\ProfessionController::index' => '?',
            'App\\Controller\\ProfessionController::new' => '?',
            'App\\Controller\\ProfessionController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CityController:delete' => '?',
            'App\\Controller\\CityController:edit' => '?',
            'App\\Controller\\CityController:index' => '?',
            'App\\Controller\\CityController:new' => '?',
            'App\\Controller\\CityController:show' => '?',
            'App\\Controller\\CraftsmanController:delete' => '?',
            'App\\Controller\\CraftsmanController:edit' => '?',
            'App\\Controller\\CraftsmanController:index' => '?',
            'App\\Controller\\CraftsmanController:new' => '?',
            'App\\Controller\\CraftsmanController:show' => '?',
            'App\\Controller\\ProfessionController:delete' => '?',
            'App\\Controller\\ProfessionController:edit' => '?',
            'App\\Controller\\ProfessionController:index' => '?',
            'App\\Controller\\ProfessionController:new' => '?',
            'App\\Controller\\ProfessionController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
