<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdnUcK1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdnUcK1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKdnUcK1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKdnUcK1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKdnUcK1\App_KernelDevDebugContainer([
    'container.build_hash' => 'KdnUcK1',
    'container.build_id' => '66e53625',
    'container.build_time' => 1687271641,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdnUcK1');
